name: CI/CD Pipeline

# This pipeline will run on any push or pull request to the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    # Use the Windows runner for compatibility with .NET and Node.js
    runs-on: windows-latest

    steps:
    # Step 1: Check out the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Node.js for the frontend tests
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    # Step 3: Install frontend dependencies and run tests
    - name: Install dependencies and run frontend tests
      working-directory: frontend
      run: |
        npm install
        npm test -- --watchAll=false

    # Step 4: Set up .NET for backend tests
    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.x'

    # Step 5: Run backend tests
    - name: Run backend tests
      working-directory: backend/CyberDashboardAPI
      run: dotnet test

    # Step 6: Set up Python and run script tests
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Step 7: Install dependencies and run Python tests
    - name: Run Python script tests
      run: |
        python -m venv venv
        venv\Scripts\activate
        pip install -r requirements.txt
        pytest tests/python_scripts
